#pragma once

#define SHELL_MAX_ARGS 16
#define SHELL_LINE_MAX 256
#define SHELL_PATH_MAX 512
#define SHELL_MAX_COMMANDS 32

#define SHELL_PATH_MAX_ENTRIES 16
#define SHELL_ALIAS_EXTENSION_MAX 64
#define SHELL_PICKER_RESULT_MAX SHELL_PATH_MAX
#define SHELL_SCRIPT_MAX_DEPTH 8
